### PR TITLE
Update run.tcl to also support KX1-325 version of the board

### PR DESCRIPTION
**Pull request by maxbab1**

### CODE REVIEW

**Comment by MarcoVogt** [comment]
@maxbab1 Did you already compile and test the firmware for the 325 version of the KX1? Does it work with the 160's xdc file?

**Comment by maxbab1** [comment]
There are two different versions of the KX1 board - they are very similar, but our version has a different fpga (one step bigger) since that was the only one we could get

I included just one additional line to build for that version

**Comment by maxbab1** [comment]
yeah, it does work now - at least i can ping the board now

is there any other test i can run without the chipboard?

**Comment by MarcoVogt** [comment]
No, not really. But this sounds almost too good to be true :). I'll check the pin assignment tables now.

**Comment by MarcoVogt** [comment]
Indeed, according to https://www.enclustra.com/assets/scripts/download.php?f=Mercury_Master_Pinout.xlsm the pinout should be identical between FPGA sizes and package types within a series of modules. Approved!

**Comment by ChristianBesp** [comment]
Great, thanks for checking, this is useful! I did not see the change in the exact model type, sorry for that. Merging now

**Pull request merged**
